
import { BankAnalytics, LoanApplication, LoanOffer } from "../types/loan";

export const mockBankAnalytics: BankAnalytics = {
  averageMonthlyInflow: 125000,
  averageMonthlyOutflow: 95000,
  cashFlowStability: 82,
  minMaintainedBalance: 30000,
  maxDebitAmount: 45000,
  maxCreditAmount: 65000,
  upiTransactionsCount: 42,
  loanRepayments: 15000,
  creditScore: 740,
  creditLimit: 500000,
  monthlyData: [
    { month: "Jan", inflow: 120000, outflow: 90000, balance: 30000 },
    { month: "Feb", inflow: 115000, outflow: 88000, balance: 27000 },
    { month: "Mar", inflow: 130000, outflow: 95000, balance: 35000 },
    { month: "Apr", inflow: 125000, outflow: 100000, balance: 25000 },
    { month: "May", inflow: 135000, outflow: 97000, balance: 38000 },
    { month: "Jun", inflow: 128000, outflow: 92000, balance: 36000 },
  ],
};

export const mockLoanOffers: LoanOffer[] = [
  {
    id: "loan-1",
    name: "Business Growth Loan",
    provider: "QuickFin Bank",
    minAmount: 100000,
    maxAmount: 500000,
    interestRate: 10.5,
    minTenure: 12,
    maxTenure: 36,
    tenureUnit: "months",
    processingFee: "1% of loan amount",
    prepaymentPenalty: "2% of outstanding balance",
    disbursementTime: "Within 48 hours",
    repaymentFrequency: "Monthly",
    repaymentMethod: "Auto-debit from bank account",
    requiredDocuments: [
      "Business PAN Card",
      "GST Registration (if applicable)",
      "Last 6 months bank statements",
      "KYC documents of proprietor/partners/directors",
    ],
    eligibilityCriteria: [
      "Business vintage of at least 1 year",
      "Minimum monthly turnover of ₹1 lakh",
      "Good banking transaction history",
      "Credit score above 700"
    ],
  },
  {
    id: "loan-2",
    name: "Working Capital Loan",
    provider: "FlexiCredit",
    minAmount: 50000,
    maxAmount: 300000,
    interestRate: 12,
    minTenure: 6,
    maxTenure: 24,
    tenureUnit: "months",
    processingFee: "1.5% of loan amount",
    prepaymentPenalty: "None after 6 months",
    disbursementTime: "Within 24 hours",
    repaymentFrequency: "Monthly",
    repaymentMethod: "Auto-debit from bank account",
    requiredDocuments: [
      "Business PAN Card",
      "Last 6 months bank statements",
      "KYC documents of proprietor/partners/directors",
    ],
    eligibilityCriteria: [
      "Business vintage of at least 8 months",
      "Minimum monthly turnover of ₹75,000",
      "Good banking transaction history",
      "Credit score above 680"
    ],
  },
  {
    id: "loan-3",
    name: "Equipment Financing",
    provider: "GrowthCapital Finance",
    minAmount: 200000,
    maxAmount: 1000000,
    interestRate: 9.75,
    minTenure: 12,
    maxTenure: 48,
    tenureUnit: "months",
    processingFee: "1% of loan amount",
    prepaymentPenalty: "2% of outstanding balance",
    disbursementTime: "Within 72 hours",
    repaymentFrequency: "Monthly",
    repaymentMethod: "Auto-debit from bank account",
    requiredDocuments: [
      "Business PAN Card",
      "GST Registration",
      "Last 1 year bank statements",
      "Equipment quotation",
      "KYC documents of proprietor/partners/directors",
    ],
    eligibilityCriteria: [
      "Business vintage of at least 2 years",
      "Minimum monthly turnover of ₹2 lakhs",
      "Good banking transaction history",
      "Credit score above 720"
    ],
  },
];

export const mockLoanApplications: LoanApplication[] = [
  {
    id: "app-1",
    loanId: "loan-1",
    loanName: "Business Growth Loan",
    provider: "QuickFin Bank",
    amount: 350000,
    tenure: 24,
    tenureUnit: "months",
    interestRate: 10.5,
    status: "disbursed",
    appliedDate: "2023-11-15T10:30:00Z",
    lastUpdated: "2023-11-18T14:20:00Z",
  },
  {
    id: "app-2",
    loanId: "loan-2",
    loanName: "Working Capital Loan",
    provider: "FlexiCredit",
    amount: 200000,
    tenure: 12,
    tenureUnit: "months",
    interestRate: 12,
    status: "review",
    appliedDate: "2023-12-05T09:15:00Z",
    lastUpdated: "2023-12-05T09:15:00Z",
  },
];
